# Generated by Django 5.2.4 on 2025-08-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
