# Generated by Django 5.2.4 on 2025-08-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.CharField(blank=True, default='English, Hindi', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='opd_time',
            field=models.CharField(blank=True, default='Mon-Fri 9AM-5PM', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
