# Generated by Django 5.2.4 on 2025-08-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='complains',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='complains',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_files/'),
        ),
        migrations.AddField(
            model_name='complains',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AddField(
            model_name='complains',
            name='municipality',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='complains',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='complains',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complains',
            name='subcategory',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='complains',
            name='ward_number',
            field=models.IntegerField(default=0),
        ),
    ]
