# Generated by Django 5.2.4 on 2025-08-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imageupload_delete_complains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('district', models.CharField(default='Unknown', max_length=100)),
                ('municipality', models.CharField(default='Unknown', max_length=100)),
                ('ward_number', models.IntegerField(default=0)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='Unknown', max_length=100)),
                ('subcategory', models.CharField(default='Unknown', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='complaint_files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
