# Generated by Django 5.2.4 on 2025-08-15 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0004_doctor_bio_doctor_hospital_doctor_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('patient_age', models.PositiveIntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(choices=[('09:00', '9:00 AM'), ('09:30', '9:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('12:00', '12:00 PM'), ('14:00', '2:00 PM'), ('14:30', '2:30 PM'), ('15:00', '3:00 PM'), ('15:30', '3:30 PM'), ('16:00', '4:00 PM'), ('16:30', '4:30 PM'), ('17:00', '5:00 PM')], max_length=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
