# Generated by Django 5.2.4 on 2025-08-13 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('district', models.CharField(default='Unknown', max_length=100)),
                ('municipality', models.CharField(default='Unknown', max_length=100)),
                ('ward_number', models.IntegerField(default=0)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='Unknown', max_length=100)),
                ('subcategory', models.CharField(default='Unknown', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='complaint_files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('seen', 'Seen'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complainFeedback.complains')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='complainFeedback.complaintcomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('seen', 'Seen'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20)),
                ('changed_by', models.CharField(default='System', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complainFeedback.complains')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
