# Generated by Django 5.2.4 on 2025-08-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complains_category_complains_district_complains_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaint_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Complains',
        ),
    ]
