# Generated by Django 5.2.4 on 2025-08-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_complains_status_complains_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintcomment',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintstatushistory',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintcomment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Complains',
        ),
        migrations.DeleteModel(
            name='ComplaintStatusHistory',
        ),
        migrations.DeleteModel(
            name='ComplaintComment',
        ),
    ]
